/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author acer
 */
public class RegisterReturn extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form RegisterRerturn
     */
    public RegisterReturn() {
        initComponents();
        this.con = DBConnect.getConnection();
        FineReturn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        panelborrower = new javax.swing.JPanel();
        borrower = new javax.swing.JLabel();
        panelbook = new javax.swing.JPanel();
        book = new javax.swing.JLabel();
        panelreturning = new javax.swing.JPanel();
        returning = new javax.swing.JLabel();
        panelborrowing = new javax.swing.JPanel();
        borrowing = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        borrowID = new app.bolivia.swing.JCTextField();
        label10 = new javax.swing.JLabel();
        bookid = new app.bolivia.swing.JCTextField();
        search = new javax.swing.JButton();
        label13 = new javax.swing.JLabel();
        returnid = new app.bolivia.swing.JCTextField();
        label14 = new javax.swing.JLabel();
        bookstatus = new javax.swing.JComboBox<>();
        fine = new javax.swing.JTextField();
        label11 = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        borrowerid = new app.bolivia.swing.JCTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        title = new app.bolivia.swing.JCTextField();
        name = new app.bolivia.swing.JCTextField();
        label8 = new javax.swing.JLabel();
        duedate = new com.toedter.calendar.JDateChooser();
        borrowdate = new com.toedter.calendar.JDateChooser();
        label5 = new javax.swing.JLabel();
        returndate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        add1 = new javax.swing.JPanel();
        addbutton = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        cancelbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        panelhome.setBackground(new java.awt.Color(0, 51, 51));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        home.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhomeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelborrower.setBackground(new java.awt.Color(0, 51, 51));
        panelborrower.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        borrower.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        borrower.setForeground(new java.awt.Color(255, 255, 255));
        borrower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/person.png"))); // NOI18N
        borrower.setText("Borrower");
        borrower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrowerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrowerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelborrowerLayout = new javax.swing.GroupLayout(panelborrower);
        panelborrower.setLayout(panelborrowerLayout);
        panelborrowerLayout.setHorizontalGroup(
            panelborrowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelborrowerLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(borrower, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelborrowerLayout.setVerticalGroup(
            panelborrowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelborrowerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borrower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelbook.setBackground(new java.awt.Color(0, 51, 51));
        panelbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        book.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        book.setForeground(new java.awt.Color(255, 255, 255));
        book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book1.png"))); // NOI18N
        book.setText("Book");
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelbookLayout = new javax.swing.GroupLayout(panelbook);
        panelbook.setLayout(panelbookLayout);
        panelbookLayout.setHorizontalGroup(
            panelbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelbookLayout.setVerticalGroup(
            panelbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelreturning.setBackground(new java.awt.Color(0, 51, 51));
        panelreturning.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        returning.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        returning.setForeground(new java.awt.Color(255, 255, 255));
        returning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/return.png"))); // NOI18N
        returning.setText("Returning");
        returning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returningMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returningMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returningMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelreturningLayout = new javax.swing.GroupLayout(panelreturning);
        panelreturning.setLayout(panelreturningLayout);
        panelreturningLayout.setHorizontalGroup(
            panelreturningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelreturningLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(returning, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelreturningLayout.setVerticalGroup(
            panelreturningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreturningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelborrowing.setBackground(new java.awt.Color(0, 51, 51));
        panelborrowing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        borrowing.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        borrowing.setForeground(new java.awt.Color(255, 255, 255));
        borrowing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrowing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list.png"))); // NOI18N
        borrowing.setText("Borrowing");
        borrowing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrowingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrowingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelborrowingLayout = new javax.swing.GroupLayout(panelborrowing);
        panelborrowing.setLayout(panelborrowingLayout);
        panelborrowingLayout.setHorizontalGroup(
            panelborrowingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelborrowingLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(borrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelborrowingLayout.setVerticalGroup(
            panelborrowingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelborrowingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borrowing, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelborrowing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelreturning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelborrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(panelhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(panelbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(panelborrower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(panelborrowing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(panelreturning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        back.setBackground(new java.awt.Color(0, 102, 102));
        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Return Information");

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lb1.setForeground(new java.awt.Color(0, 102, 102));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("Fine");

        borrowID.setBackground(new java.awt.Color(255, 255, 255));
        borrowID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 102)));
        borrowID.setForeground(new java.awt.Color(0, 0, 0));
        borrowID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowIDActionPerformed(evt);
            }
        });

        label10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 102, 102));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("BookStatus");

        bookid.setBackground(new java.awt.Color(255, 255, 255));
        bookid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 102)));
        bookid.setForeground(new java.awt.Color(0, 0, 0));
        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        search.setForeground(new java.awt.Color(0, 102, 102));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        label13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label13.setForeground(new java.awt.Color(0, 102, 102));
        label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label13.setText("BorrowerID");

        returnid.setBackground(new java.awt.Color(255, 255, 255));
        returnid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 102)));
        returnid.setForeground(new java.awt.Color(0, 0, 0));
        returnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnidActionPerformed(evt);
            }
        });

        label14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label14.setForeground(new java.awt.Color(0, 102, 102));
        label14.setText("BookID");

        bookstatus.setBackground(new java.awt.Color(255, 255, 255));
        bookstatus.setForeground(new java.awt.Color(0, 102, 102));
        bookstatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bookstatusItemStateChanged(evt);
            }
        });
        bookstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookstatusActionPerformed(evt);
            }
        });

        fine.setBackground(new java.awt.Color(255, 255, 255));
        fine.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        fine.setForeground(new java.awt.Color(0, 102, 102));
        fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fineActionPerformed(evt);
            }
        });

        label11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 102, 102));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("BorrowID");

        label15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label15.setForeground(new java.awt.Color(0, 102, 102));
        label15.setText("ReturnID");

        borrowerid.setBackground(new java.awt.Color(255, 255, 255));
        borrowerid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 102)));
        borrowerid.setForeground(new java.awt.Color(0, 0, 0));
        borrowerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borroweridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(79, 79, 79))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borrowerid, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(search))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label11)
                                    .addComponent(label14))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(borrowID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnid, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label10)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(lb1)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fine))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrowerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrowID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookstatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Borrow Information");

        label1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 102, 102));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Title");

        label2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 102, 102));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Name");

        label4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 102, 102));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("ReturnDate");

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 102)));
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 102)));
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        label8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label8.setForeground(new java.awt.Color(0, 102, 102));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("DueDate");

        duedate.setBackground(new java.awt.Color(255, 255, 255));
        duedate.setForeground(new java.awt.Color(0, 102, 102));

        borrowdate.setBackground(new java.awt.Color(255, 255, 255));
        borrowdate.setForeground(new java.awt.Color(0, 102, 102));

        label5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 102, 102));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("BorrowDate");

        returndate.setBackground(new java.awt.Color(255, 255, 255));
        returndate.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrowdate, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(duedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(returndate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(borrowdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(duedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(returndate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register Return Book");

        add1.setBackground(new java.awt.Color(0, 102, 102));
        add1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        addbutton.setBackground(new java.awt.Color(0, 102, 102));
        addbutton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        addbutton.setForeground(new java.awt.Color(255, 255, 255));
        addbutton.setText("Return");
        addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout add1Layout = new javax.swing.GroupLayout(add1);
        add1.setLayout(add1Layout);
        add1Layout.setHorizontalGroup(
            add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        add1Layout.setVerticalGroup(
            add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cancel.setBackground(new java.awt.Color(0, 102, 102));
        cancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        cancelbutton.setBackground(new java.awt.Color(0, 102, 102));
        cancelbutton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cancelbutton.setForeground(new java.awt.Color(255, 255, 255));
        cancelbutton.setText("Cancel");

        javax.swing.GroupLayout cancelLayout = new javax.swing.GroupLayout(cancel);
        cancel.setLayout(cancelLayout);
        cancelLayout.setHorizontalGroup(
            cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        cancelLayout.setVerticalGroup(
            cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        DashBoardForm dashform = new DashBoardForm();
        dashform.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        Color clr = new Color(0,153,153);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        Color clr = new Color(0,51,51);
        panelhome.setBackground(clr);
    }//GEN-LAST:event_homeMouseExited

    private void borrowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerMouseClicked
        Borrower borrowerform = new Borrower();
        borrowerform.setVisible(true);
        dispose();
    }//GEN-LAST:event_borrowerMouseClicked

    private void borrowerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerMouseEntered
        Color clr = new Color(0,153,153);
        panelborrower.setBackground(clr);
    }//GEN-LAST:event_borrowerMouseEntered

    private void borrowerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerMouseExited
        Color clr = new Color(0,51,51);
        panelborrower.setBackground(clr);
    }//GEN-LAST:event_borrowerMouseExited

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked
        BookManagement bookform = new BookManagement();
        bookform.setVisible(true);
        dispose();
    }//GEN-LAST:event_bookMouseClicked

    private void bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseEntered
        Color clr = new Color(0,153,153);
        panelbook.setBackground(clr);
    }//GEN-LAST:event_bookMouseEntered

    private void bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseExited
        Color clr = new Color(0,51,51);
        panelbook.setBackground(clr);
    }//GEN-LAST:event_bookMouseExited

    private void returningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returningMouseClicked
        ReturningBook returningform = new ReturningBook();
        returningform.setVisible(true);
        dispose();
    }//GEN-LAST:event_returningMouseClicked

    private void returningMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returningMouseEntered
        Color clr = new Color(0,153,153);
        panelreturning.setBackground(clr);
    }//GEN-LAST:event_returningMouseEntered

    private void returningMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returningMouseExited
        Color clr = new Color(0,51,51);
        panelreturning.setBackground(clr);
    }//GEN-LAST:event_returningMouseExited

    private void borrowingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowingMouseClicked
        BorrowingBook borrowingform = new BorrowingBook();
        borrowingform.setVisible(true);
        dispose();
    }//GEN-LAST:event_borrowingMouseClicked

    private void borrowingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowingMouseEntered
        Color clr = new Color(0,153,153);
        panelborrowing.setBackground(clr);
    }//GEN-LAST:event_borrowingMouseEntered

    private void borrowingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowingMouseExited
        Color clr = new Color(0,51,51);
        panelborrowing.setBackground(clr);
    }//GEN-LAST:event_borrowingMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        BorrowingBook borrowForm = new BorrowingBook();
        borrowForm.setVisible(true);
        dispose(); // Close the Book form
    }//GEN-LAST:event_backActionPerformed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        BorrowingBook borrowingForm = new BorrowingBook();
        borrowingForm.setVisible(true);
        dispose(); // Close the Book form
    }//GEN-LAST:event_cancelMouseClicked

    private void returnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnidActionPerformed

    
    public void FineReturn(){
        String query = "SELECT BookDamage FROM bookdamagerule";
        try{
            con = DBConnect.getConnection();
            pst = con.prepareStatement(query);
            rs = pst.executeQuery();
            bookstatus.removeAll();
            
            while(rs.next()){
                bookstatus.addItem(rs.getString(1));
            }
        }catch(SQLException e){
            Logger.getLogger(RegisterReturn.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    String query = "SELECT BorrowID, BookID, BorrowDate, DueDate FROM borrowingbook WHERE BorrowerID = ?";
    String sql = "SELECT name from Borrower where BorrowerID = ?";
    String sql1 = "Select b.Title FROM borrowingbook bb Join book b On bb.BookID = b.BookID Where bb.BorrowerID = ?";
        try{
            this.pst = this.con.prepareStatement(query);
            this.pst.setString(1, this.borrowerid.getText());
            this.rs = this.pst.executeQuery();
            
            if (this.rs.next()) {
                String add1 = this.rs.getString("BorrowID");
                borrowID.setText(add1);
                String add2 = this.rs.getString("BookID");
                bookid.setText(add2);
                java.sql.Date add3 = this.rs.getDate("BorrowDate");
                borrowdate.setDate(add3);
                java.sql.Date add4 = this.rs.getDate("DueDate");
                duedate.setDate(add4);
            }
                this.rs.close();
                this.pst.close();

                this.pst = this.con.prepareStatement(sql);
                this.pst.setString(1, this.borrowerid.getText());
                this.rs = this.pst.executeQuery();
                if (this.rs.next()) {
                String add5 = this.rs.getString("Name");
                name.setText(add5);
            }
                this.rs.close();
                this.pst.close();

                this.pst = this.con.prepareStatement(sql1);
                this.pst.setString(1, this.borrowerid.getText());
                this.rs = this.pst.executeQuery();
                if (this.rs.next()) {
                String add6 = this.rs.getString("Title");
                title.setText(add6);
            }else{
           JOptionPane.showMessageDialog((Component)null, "Borrower ID Not Found");
         }
       } catch (SQLException ex) {
           Logger.getLogger(RegisterBorrow.class.getName()).log(Level.SEVERE, null, ex);
       }finally {
         try {
            this.rs.close();
            this.pst.close();
         } catch (Exception var15) {
       }
     }
    }//GEN-LAST:event_searchActionPerformed

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookidActionPerformed

    private void borrowIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowIDActionPerformed

    private void bookstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookstatusActionPerformed

    private void bookstatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bookstatusItemStateChanged
        try{
        con = DBConnect.getConnection();
        String BookStatus = bookstatus.getSelectedItem().toString();
        pst = con.prepareStatement("select FineAmount from bookdamagerule where BookDamage = ?");
        pst.setString (1, BookStatus);
        ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                String Amount;
                Amount = rs.getString(1);
                fine.setText(Amount);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterReturn.class.getName()).log(Level.SEVERE, null, ex);
        
        } 
    }//GEN-LAST:event_bookstatusItemStateChanged

    private void fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fineActionPerformed

    private void borroweridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borroweridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borroweridActionPerformed

    private void addbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseClicked
        if(validateRegisterBook()== true){
            insertToReturningBook();
   
        }
    }//GEN-LAST:event_addbuttonMouseClicked

    
    public void insertToReturningBook(){
        String BorrowerName = name.getText();
        String FineAmount = fine.getText();
        String BookStatus = (String) bookstatus.getSelectedItem();

        
        
        java.util.Date DDate = duedate.getDate();
        java.sql.Date DueDate = new java.sql.Date(DDate.getTime());

        java.util.Date RDate = returndate.getDate();
        java.sql.Date ReturnDate = new java.sql.Date(RDate.getTime());
        
        Integer BorrowerID = Integer.parseInt(returnid.getText());
        Integer BorrowID = Integer.parseInt(borrowID.getText());
        Integer BookID = Integer.parseInt(bookid.getText());
        Integer ReturnID = Integer.parseInt(returnid.getText());

        try{
            Connection con= DBConnect.getConnection();
            String query = "insert into returningbook values (?,?,?,?,?,?,?,?,?);";
            PreparedStatement ps = con.prepareStatement(query);
            
            ps.setInt(1, ReturnID);
            ps.setInt(2, BookID);
            ps.setInt(3, BorrowerID);
            ps.setString(4, BorrowerName);
            ps.setInt(5, BorrowID);
            ps.setDate(6, ReturnDate);
            ps.setString(7, BookStatus);
            ps.setString(8, FineAmount);
            ps.setDate(9, DueDate);
            
            
            int updateRowCount = ps.executeUpdate();
            
            if(updateRowCount != 0){
                JOptionPane.showMessageDialog(null,"Return Book Successfully","Add Borrower",3);
            }else{
                JOptionPane.showMessageDialog(null,"Return Book Fail","Add Borrower",2);
            }
        }
         catch (SQLException ex) {
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public boolean validateRegisterBook(){
        String BorrowerName = name.getText();
        String FineAmount = fine.getText();
        String BookStatus = (String) bookstatus.getSelectedItem();
       
        
       if(BorrowerName.equals("")){
       JOptionPane.showMessageDialog(this,"Enter your name","Empty field",0);
       return false;
   }
       if(FineAmount.equals("")){
       JOptionPane.showMessageDialog(this,"Enter your find amount","Empty field",0);
       return false;
   }
       if(BookStatus.equals("")){
       JOptionPane.showMessageDialog(this,"Choose your book status","Empty field",0);
       return false;
       }
       return true;
    }
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add1;
    private javax.swing.JLabel addbutton;
    private javax.swing.JButton back;
    private javax.swing.JLabel book;
    private app.bolivia.swing.JCTextField bookid;
    private javax.swing.JComboBox<String> bookstatus;
    private app.bolivia.swing.JCTextField borrowID;
    private com.toedter.calendar.JDateChooser borrowdate;
    private javax.swing.JLabel borrower;
    private app.bolivia.swing.JCTextField borrowerid;
    private javax.swing.JLabel borrowing;
    private javax.swing.JPanel cancel;
    private javax.swing.JLabel cancelbutton;
    private com.toedter.calendar.JDateChooser duedate;
    private javax.swing.JTextField fine;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel lb1;
    private app.bolivia.swing.JCTextField name;
    private javax.swing.JPanel panelbook;
    private javax.swing.JPanel panelborrower;
    private javax.swing.JPanel panelborrowing;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelreturning;
    private com.toedter.calendar.JDateChooser returndate;
    private app.bolivia.swing.JCTextField returnid;
    private javax.swing.JLabel returning;
    private javax.swing.JButton search;
    private app.bolivia.swing.JCTextField title;
    // End of variables declaration//GEN-END:variables
}
